#!/bin/bash

# autogenerated script of NetPlant
# ExecutionQueue ID: 7

# rename existing user 
ssh root@127.0.0.1 'usermod -l johnyD johnyCage' || exit 1
# change password for existing user! 
ssh root@127.0.0.1 'echo -e "new pass for johny\nnew pass for johny" | (passwd --stdin johnyCage)' || exit 1
# create new user 
ssh root@127.0.0.1 'useradd -p \`openssl passwd -1 yayaya\` yep' || exit 1
ssh root@127.0.0.1 'chsh --shell=/bin/false yep' || exit 1
